/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnidadDos;
import UnidadDos.MetodoBiseccion.*;
/**
 *
 * @author cobak
 */



import UnidadUno.metodoss;

public class varInterpolacionNewton extends javax.swing.JFrame {

    /**
     * Creates new form varBiseccion
     */
    
    //se crean las variables
    
    private double limiteInferior,limiteSuperior,Tolerancia;
    private double varUno,VarDos,Var3,Var4;
    private String signoUno="";
    private String signoDos="";
    private String Resultado;
    
    MetodoBiseccion cal =new MetodoBiseccion();
    
    
    public varInterpolacionNewton() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExtremoInferior = new javax.swing.JLabel();
        ExtremoSuperior = new javax.swing.JLabel();
        ExtremoSuperior1 = new javax.swing.JLabel();
        ExtremoSuperior2 = new javax.swing.JLabel();
        ExtremoSuperior3 = new javax.swing.JLabel();
        BotonCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        varInf = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        VarSup = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        varTol = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        intTres = new javax.swing.JTextPane();
        ExtremoInferior1 = new javax.swing.JLabel();
        ExtremoInferior2 = new javax.swing.JLabel();
        ExtremoInferior3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        intCuatro = new javax.swing.JTextPane();
        ExtremoSuperior5 = new javax.swing.JLabel();
        ExtremoSuperior6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        intUno = new javax.swing.JTextPane();
        ExtremoSuperior9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        intdos = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("INSERTAR LAS VARIABLES DEL ");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("METODO DE BISECCION");

        ExtremoInferior.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoInferior.setText("Xi");

        ExtremoSuperior.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior.setText("Xs");

        ExtremoSuperior1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior1.setText("Tolerancia: ");

        ExtremoSuperior2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior2.setText("Funcion: ");

        ExtremoSuperior3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior3.setText("x");

        BotonCalcular.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        BotonCalcular.setText("Calcular");
        BotonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalcularActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(varInf);

        jScrollPane2.setViewportView(VarSup);

        jScrollPane3.setViewportView(varTol);

        jScrollPane8.setViewportView(intTres);

        ExtremoInferior1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoInferior1.setText("Primera Varible: ");

        ExtremoInferior2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoInferior2.setText("Segunda Varible: ");

        ExtremoInferior3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoInferior3.setText("Variable Comun: ");

        jScrollPane9.setViewportView(intCuatro);

        ExtremoSuperior5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior5.setText("x");

        ExtremoSuperior6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior6.setText("*");

        jScrollPane6.setViewportView(intUno);

        ExtremoSuperior9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior9.setText("*");

        jScrollPane7.setViewportView(intdos);

        jToggleButton1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jToggleButton1.setText("Menu");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jToggleButton2.setText("Ventana anterior");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExtremoInferior3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExtremoInferior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExtremoSuperior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExtremoSuperior1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ExtremoInferior1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtremoSuperior9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExtremoSuperior3))
                            .addComponent(ExtremoSuperior2))
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(ExtremoInferior2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExtremoSuperior5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExtremoSuperior6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonCalcular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(ExtremoInferior))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExtremoSuperior)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExtremoSuperior1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(ExtremoSuperior2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ExtremoInferior1)
                                .addComponent(ExtremoSuperior3)
                                .addComponent(ExtremoSuperior9)))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ExtremoInferior2)
                        .addComponent(ExtremoSuperior5)
                        .addComponent(ExtremoSuperior6))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExtremoInferior3)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCalcular)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalcularActionPerformed
        limiteInferior =Double.parseDouble(varInf.getText());// TODO add your handling code here:
        limiteSuperior=Double.parseDouble(VarSup.getText());
        Tolerancia = Double.parseDouble(varTol.getText()) ;
        
        //variables para contruir la funcion de evaluacion
        //variables Enteros
        varUno = Double.parseDouble(intUno.getText());
        VarDos = Double.parseDouble(intdos.getText());
        Var3 = Double.parseDouble(intTres.getText());
        Var4 = Double.parseDouble(intCuatro.getText());
    }//GEN-LAST:event_BotonCalcularActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        vistas abrir = new vistas();
        abrir.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
       
        EscogerInterpolacion abrir = new EscogerInterpolacion();
        abrir.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCalcular;
    private javax.swing.JLabel ExtremoInferior;
    private javax.swing.JLabel ExtremoInferior1;
    private javax.swing.JLabel ExtremoInferior2;
    private javax.swing.JLabel ExtremoInferior3;
    private javax.swing.JLabel ExtremoSuperior;
    private javax.swing.JLabel ExtremoSuperior1;
    private javax.swing.JLabel ExtremoSuperior2;
    private javax.swing.JLabel ExtremoSuperior3;
    private javax.swing.JLabel ExtremoSuperior5;
    private javax.swing.JLabel ExtremoSuperior6;
    private javax.swing.JLabel ExtremoSuperior9;
    private javax.swing.JTextPane VarSup;
    private javax.swing.JTextPane intCuatro;
    private javax.swing.JTextPane intTres;
    private javax.swing.JTextPane intUno;
    private javax.swing.JTextPane intdos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextPane varInf;
    private javax.swing.JTextPane varTol;
    // End of variables declaration//GEN-END:variables
}
