/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnidadDos;

/**
 *
 * @author cobak
 */
public class varInterpolacionSecante extends javax.swing.JFrame {

    /**
     * Creates new form varBiseccion
     */
    public varInterpolacionSecante() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExtremoInferior = new javax.swing.JLabel();
        ExtremoSuperior = new javax.swing.JLabel();
        ExtremoSuperior1 = new javax.swing.JLabel();
        ExtremoSuperior2 = new javax.swing.JLabel();
        ExtremoSuperior3 = new javax.swing.JLabel();
        ExtremoSuperior4 = new javax.swing.JLabel();
        ExtremoSuperior7 = new javax.swing.JLabel();
        ExtremoSuperior8 = new javax.swing.JLabel();
        ExtremoInferiorUno = new javax.swing.JTextField();
        ExtremoSuperiorUno = new javax.swing.JTextField();
        Tolerancia = new javax.swing.JTextField();
        ExponenteUno = new javax.swing.JTextField();
        ExponenteDos = new javax.swing.JTextField();
        Comun = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("INSERTAR LAS VARIABLES DEL ");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("METODO DE BISECCION");

        ExtremoInferior.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoInferior.setText("Xi");

        ExtremoSuperior.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior.setText("Xs");

        ExtremoSuperior1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior1.setText("Tolerancia: ");

        ExtremoSuperior2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior2.setText("Funcion: ");

        ExtremoSuperior3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior3.setText("X");

        ExtremoSuperior4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior4.setText("+");

        ExtremoSuperior7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior7.setText("X");

        ExtremoSuperior8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExtremoSuperior8.setText("+");

        ExtremoInferiorUno.setText("insertar valor");
        ExtremoInferiorUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtremoInferiorUnoActionPerformed(evt);
            }
        });

        ExtremoSuperiorUno.setText("insertar valor");
        ExtremoSuperiorUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtremoSuperiorUnoActionPerformed(evt);
            }
        });

        Tolerancia.setText("insertar valor");
        Tolerancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToleranciaActionPerformed(evt);
            }
        });

        ExponenteUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExponenteUnoActionPerformed(evt);
            }
        });

        ExponenteDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExponenteDosActionPerformed(evt);
            }
        });

        Comun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunActionPerformed(evt);
            }
        });

        botonCalcular.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExtremoSuperior1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ExtremoInferior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExtremoInferiorUno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ExtremoSuperior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExtremoSuperiorUno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonCalcular)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ExtremoSuperior2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(ExtremoSuperior3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ExtremoSuperior4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ExtremoSuperior7)
                                        .addGap(35, 35, 35)
                                        .addComponent(ExtremoSuperior8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Comun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ExponenteUno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(ExponenteDos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(ExtremoInferior))
                    .addComponent(ExtremoInferiorUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExtremoSuperior)
                    .addComponent(ExtremoSuperiorUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExtremoSuperior1)
                    .addComponent(Tolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(ExtremoSuperior2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ExponenteUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExponenteDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ExtremoSuperior7)
                            .addComponent(ExtremoSuperior8)
                            .addComponent(Comun, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ExtremoSuperior3)
                        .addComponent(ExtremoSuperior4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExtremoInferiorUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtremoInferiorUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtremoInferiorUnoActionPerformed

    private void ExtremoSuperiorUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtremoSuperiorUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtremoSuperiorUnoActionPerformed

    private void ToleranciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToleranciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToleranciaActionPerformed

    private void ExponenteUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExponenteUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExponenteUnoActionPerformed

    private void ExponenteDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExponenteDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExponenteDosActionPerformed

    private void ComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Comun;
    private javax.swing.JTextField ExponenteDos;
    private javax.swing.JTextField ExponenteUno;
    private javax.swing.JLabel ExtremoInferior;
    private javax.swing.JTextField ExtremoInferiorUno;
    private javax.swing.JLabel ExtremoSuperior;
    private javax.swing.JLabel ExtremoSuperior1;
    private javax.swing.JLabel ExtremoSuperior2;
    private javax.swing.JLabel ExtremoSuperior3;
    private javax.swing.JLabel ExtremoSuperior4;
    private javax.swing.JLabel ExtremoSuperior7;
    private javax.swing.JLabel ExtremoSuperior8;
    private javax.swing.JTextField ExtremoSuperiorUno;
    private javax.swing.JTextField Tolerancia;
    private javax.swing.JButton botonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
