/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnidadUno;
import javax.swing.JOptionPane;
import UnidadUno.metodoss;

/**
 *
 * @author cobak
 */
public class ventenaCuarta extends javax.swing.JFrame {

    
    private double resultadoUnoAbs,resultadoUnoRel,resultadoDosAbs,resultadoDosRel;
    int Decimales;
    private double valorUnoAbs,valorUnoRel,valorDosAbs,valorDosRel;
    private String resultUnoAbs,resultUnoRel,resultDosRel,resultDosAbs;
    metodoss cal =  new metodoss();
  
    public ventenaCuarta() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        ventanaSecundaria ventana = new ventanaSecundaria();
        recibiErrorAbsoultoTruncamiento.setText(ventana.enviarUnoAbs);
        recibiErrorRelativoTruncamiento.setText(ventana.enviarUnoRel);
        recibiErrorAbsoultoRedondeo.setText(ventana.enviarDosAbs);
        recibiErrorRelativoRedondeo.setText(ventana.enviarDosRel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        trucamiento = new javax.swing.JButton();
        recibiErrorAbsoultoTruncamiento = new javax.swing.JTextField();
        redondeo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        decimales = new javax.swing.JTextField();
        recibiErrorRelativoTruncamiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        recibiErrorAbsoultoRedondeo = new javax.swing.JTextField();
        recibiErrorRelativoRedondeo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Escoge una opcion");

        trucamiento.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        trucamiento.setText("calcular truncamiento");
        trucamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trucamientoActionPerformed(evt);
            }
        });

        redondeo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        redondeo.setText("calcular Redondeo");
        redondeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redondeoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Ingresar Cantidad de decimales: ");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Erros Absoluto:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Erros Relativo:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Erros Absoluto:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Erros Relativo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trucamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(redondeo)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recibiErrorAbsoultoTruncamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recibiErrorRelativoTruncamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(recibiErrorRelativoRedondeo, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(recibiErrorAbsoultoRedondeo))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(decimales, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(decimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recibiErrorAbsoultoTruncamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(recibiErrorRelativoTruncamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recibiErrorAbsoultoRedondeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(recibiErrorRelativoRedondeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trucamiento)
                    .addComponent(redondeo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redondeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redondeoActionPerformed
    valorDosAbs = Double.parseDouble(recibiErrorAbsoultoRedondeo.getText());   
    valorDosRel = Double.parseDouble(recibiErrorRelativoRedondeo.getText());  
    Decimales= Integer.parseInt(decimales.getText());
    
    resultadoDosAbs=cal.redondearDecimales(valorDosAbs, Decimales);
    resultadoDosRel=cal.redondearDecimales(valorDosRel, Decimales);
        
    resultDosAbs=String.valueOf(resultadoDosAbs);
    resultDosRel=String.valueOf(resultadoDosRel);
        
    recibiErrorAbsoultoRedondeo.setText(resultDosAbs);
    recibiErrorRelativoRedondeo.setText(resultDosRel);
    
    }//GEN-LAST:event_redondeoActionPerformed

    private void trucamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trucamientoActionPerformed
    Decimales= Integer.parseInt(decimales.getText());
    valorUnoAbs = Double.parseDouble(recibiErrorAbsoultoTruncamiento.getText());      
    valorUnoRel = Double.parseDouble(recibiErrorRelativoTruncamiento.getText());   
    
    resultadoUnoAbs=cal.truncamientoDecimal(Decimales, valorUnoAbs);
    resultadoUnoRel=cal.truncamientoDecimal(Decimales, valorUnoRel);
        
    resultUnoAbs=String.valueOf(resultadoUnoAbs);
    resultUnoRel=String.valueOf(resultadoUnoRel);
        
    recibiErrorAbsoultoTruncamiento.setText(resultUnoAbs);
    recibiErrorRelativoTruncamiento.setText(resultUnoRel);
    }//GEN-LAST:event_trucamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventenaCuarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventenaCuarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventenaCuarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventenaCuarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventenaCuarta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField decimales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField recibiErrorAbsoultoRedondeo;
    public static javax.swing.JTextField recibiErrorAbsoultoTruncamiento;
    public static javax.swing.JTextField recibiErrorRelativoRedondeo;
    public static javax.swing.JTextField recibiErrorRelativoTruncamiento;
    private javax.swing.JButton redondeo;
    private javax.swing.JButton trucamiento;
    // End of variables declaration//GEN-END:variables
}
